#
# Copyright 2023 Datastrato.
# This software is licensed under the Apache License version 2.
#

FROM trinodb/trino:426
LABEL maintainer="support@datastrato.com"

RUN rm -rf /usr/lib/trino/plugin/accumulo 
RUN rm -rf /usr/lib/trino/plugin/blackhole
RUN rm -rf /usr/lib/trino/plugin/delta-lake
RUN rm -rf /usr/lib/trino/plugin/example-http
RUN rm -rf /usr/lib/trino/plugin/geospatial
RUN rm -rf /usr/lib/trino/plugin/kafka
RUN rm -rf /usr/lib/trino/plugin/local-file
RUN rm -rf /usr/lib/trino/plugin/ml
RUN rm -rf /usr/lib/trino/plugin/mysql-event-listener
RUN rm -rf /usr/lib/trino/plugin/phoenix5
RUN rm -rf /usr/lib/trino/plugin/prometheus
RUN rm -rf /usr/lib/trino/plugin/redshift
RUN rm -rf /usr/lib/trino/plugin/singlestore
RUN rm -rf /usr/lib/trino/plugin/thrift
RUN rm -rf /usr/lib/trino/plugin/atop 
RUN rm -rf /usr/lib/trino/plugin/cassandra
RUN rm -rf /usr/lib/trino/plugin/druid
RUN rm -rf /usr/lib/trino/plugin/exchange-filesystem
RUN rm -rf /usr/lib/trino/plugin/google-sheets
RUN rm -rf /usr/lib/trino/plugin/http-event-listener
RUN rm -rf /usr/lib/trino/plugin/ignite
RUN rm -rf /usr/lib/trino/plugin/kinesis
RUN rm -rf /usr/lib/trino/plugin/mongodb
RUN rm -rf /usr/lib/trino/plugin/oracle
RUN rm -rf /usr/lib/trino/plugin/pinot
RUN rm -rf /usr/lib/trino/plugin/raptor-legacy
RUN rm -rf /usr/lib/trino/plugin/resource-group-managers
RUN rm -rf /usr/lib/trino/plugin/sqlserver
RUN rm -rf /usr/lib/trino/plugin/bigquery
RUN rm -rf /usr/lib/trino/plugin/clickhouse
RUN rm -rf /usr/lib/trino/plugin/elasticsearch
RUN rm -rf /usr/lib/trino/plugin/exchange-hdfs
RUN rm -rf /usr/lib/trino/plugin/hudi
RUN rm -rf /usr/lib/trino/plugin/kudu
RUN rm -rf /usr/lib/trino/plugin/password-authenticators
RUN rm -rf /usr/lib/trino/plugin/postgresql
RUN rm -rf /usr/lib/trino/plugin/redis
RUN rm -rf /usr/lib/trino/plugin/session-property-managers
RUN rm -rf /usr/lib/trino/plugin/teradata-functions
