select count(*) from call_center;
select count(*) from catalog_page;
select count(*) from catalog_returns;
select count(*) from catalog_sales;
select count(*) from customer;
select count(*) from customer_address;
select count(*) from customer_demographics;
select count(*) from date_dim;
select count(*) from household_demographics;
select count(*) from income_band;
select count(*) from inventory;
select count(*) from item;
select count(*) from promotion;
select count(*) from reason;
select count(*) from ship_mode;
select count(*) from store;
select count(*) from store_returns;
select count(*) from store_sales;
select count(*) from time_dim;
select count(*) from warehouse;
select count(*) from web_page;
select count(*) from web_returns;
select count(*) from web_sales;
select count(*) from web_site;

select * from call_center limit 10;
select * from catalog_page limit 10;
select * from catalog_returns limit 10;
select * from catalog_sales limit 10;
select * from customer limit 10;
select * from customer_address limit 10;
select * from customer_demographics limit 10;
select * from date_dim limit 10;
select * from household_demographics limit 10;
select * from income_band limit 10;
select * from inventory limit 10;
select * from item limit 10;
select * from promotion limit 10;
select * from reason limit 10;
select * from ship_mode limit 10;
select * from store limit 10;
select * from store_returns limit 10;
select * from store_sales limit 10;
select * from time_dim limit 10;
select * from warehouse limit 10;
select * from web_page limit 10;
select * from web_returns limit 10;
select * from web_sales limit 10;
select * from web_site limit 10;
