#
# Copyright 2023 Datastrato Pvt Ltd.
# This software is licensed under the Apache License version 2.
#
version: '3.0'
services:
  trino:
    image: datastrato/gravitino-ci-trino:0.1.2
    networks:
      - trino-net
    container_name: trino-ci-trino
    environment:
      - HADOOP_USER_NAME=root
      - GRAVITINO_HOST_IP=host.docker.internal
      - GRAVITINO_HOST_PORT=${GRAVITINO_SERVER_PORT:-8090}
      - GRAVITINO_METALAKE_NAME=test
      - HIVE_HOST_IP=hive
    entrypoint:  /bin/bash /tmp/trino/init.sh
    volumes:
      - ./init/trino:/tmp/trino
      - ../../../trino-connector/build/libs:/usr/lib/trino/plugin/gravitino
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - hive
      - postgresql
      - mysql

  hive:
    image: datastrato/gravitino-ci-hive:0.1.7
    networks:
      - trino-net
    container_name: trino-ci-hive
    environment:
      - HADOOP_USER_NAME=root
    entrypoint:  /bin/bash /tmp/hive/init.sh
    volumes:
      - ./init/hive:/tmp/hive
    healthcheck:
      test: ["CMD", "/tmp/check-status.sh"]
      interval: 10s
      timeout: 60s
      retries: 5

  postgresql:
    image: postgres:13
    container_name: trino-ci-postgresql
    restart: always
    environment:
      POSTGRES_USER: trino
      POSTGRES_PASSWORD: ds123
      ALLOW_IP_RANGE: 0.0.0.0/0
    networks:
      - trino-net
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d/

  mysql:
    image: mysql:8.0
    container_name: trino-ci-mysql
    networks:
      - trino-net
    volumes:
      - ./init/mysql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ds123
      MYSQL_USER: trino
      MYSQL_PASSWORD: ds123
      MYSQL_DATABASE: gt_db
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1

networks:
  trino-net:
    driver: bridge
    name: trino-net
