/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.apache.gravitino.credential;

import java.lang.reflect.Constructor;
import java.util.Map;

/**
 * An abstract base class for {@link CredentialProvider} implementations that delegate the actual
 * credential generation to a {@link CredentialGenerator}. It handles the lazy and reflective
 * loading of the generator to isolate heavy dependencies.
 *
 * @param <T> The type of credential generated by this provider.
 */
public abstract class CredentialProviderDelegator<T extends Credential>
    implements CredentialProvider {

  /**
   * The properties used by the generator to generate the credential.
   */
  protected Map<String, String> properties;
  private volatile CredentialGenerator<T> generator;

  @Override
  public void initialize(Map<String, String> properties) {
    this.properties = properties;
  }

  @Override
  public Credential getCredential(CredentialContext context) {
    if (generator == null) {
      synchronized (this) {
        if (generator == null) {
          this.generator = loadGenerator();
        }
      }
    }

    try {
      return generator.generate(properties, context);
    } catch (Exception e) {
      throw new RuntimeException(
          "Failed to generate credential using " + getGeneratorClassName(), e);
    }
  }

  /**
   * Lazily loads and returns an instance of the {@link CredentialGenerator}. This default
   * implementation uses reflection and a no-argument constructor (public or non-public).
   *
   * @return An instance of the credential generator.
   * @throws RuntimeException if the generator cannot be instantiated.
   */
  @SuppressWarnings("unchecked")
  private CredentialGenerator<T> loadGenerator() {
    try {
      Class<?> generatorClass = Class.forName(getGeneratorClassName());
      Constructor<?> constructor = generatorClass.getDeclaredConstructor();
      constructor.setAccessible(true);
      return (CredentialGenerator<T>) constructor.newInstance();
    } catch (Exception e) {
      throw new RuntimeException(
          "Failed to load or instantiate CredentialGenerator: " + getGeneratorClassName(), e);
    }
  }
}
