# See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

name: Improvement
title: "[Improvement] "
description: Suggest an improvement on performance, code quality, user experience, etc
labels: [ "improvement" ]
body:

  - type: textarea
    attributes:
      label: What would you like to be improved?
      placeholder: >
        Please describe the problem you see and how it is needed to be improved.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How should we improve?
      placeholder: >
        Please provide the solution if you have thoughts.
    validations:
      required: false
