# coding: utf-8

"""
    Gravitino REST API

    Defines the specification for the first version of the Gravitino REST API.   # noqa: E501

    The version of the OpenAPI document: 0.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from com.datastrato.gravitino.client import schemas  # noqa: F401


class AuditDto(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Audit information for a Gravitino resource.
    """


    class MetaOapg:
        
        class properties:
            creator = schemas.StrSchema
            createTime = schemas.DateTimeSchema
            lastModifier = schemas.StrSchema
            lastModifiedTime = schemas.DateTimeSchema
            __annotations__ = {
                "creator": creator,
                "createTime": createTime,
                "lastModifier": lastModifier,
                "lastModifiedTime": lastModifiedTime,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["creator"]) -> MetaOapg.properties.creator: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createTime"]) -> MetaOapg.properties.createTime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lastModifier"]) -> MetaOapg.properties.lastModifier: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["lastModifiedTime"]) -> MetaOapg.properties.lastModifiedTime: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["creator", "createTime", "lastModifier", "lastModifiedTime", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["creator"]) -> typing.Union[MetaOapg.properties.creator, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createTime"]) -> typing.Union[MetaOapg.properties.createTime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lastModifier"]) -> typing.Union[MetaOapg.properties.lastModifier, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["lastModifiedTime"]) -> typing.Union[MetaOapg.properties.lastModifiedTime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["creator", "createTime", "lastModifier", "lastModifiedTime", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        creator: typing.Union[MetaOapg.properties.creator, str, schemas.Unset] = schemas.unset,
        createTime: typing.Union[MetaOapg.properties.createTime, str, datetime, schemas.Unset] = schemas.unset,
        lastModifier: typing.Union[MetaOapg.properties.lastModifier, str, schemas.Unset] = schemas.unset,
        lastModifiedTime: typing.Union[MetaOapg.properties.lastModifiedTime, str, datetime, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AuditDto':
        return super().__new__(
            cls,
            *_args,
            creator=creator,
            createTime=createTime,
            lastModifier=lastModifier,
            lastModifiedTime=lastModifiedTime,
            _configuration=_configuration,
            **kwargs,
        )
