#!/usr/bin/env bash
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

set -euo pipefail

GRAVITINO_HOME="${GRAVITINO_HOME:-/Users/fanng/deploy/chinamobile/package}"
GRAVITINO_CONF_FILE="${GRAVITINO_CONF_FILE:-${GRAVITINO_HOME}/conf/gravitino.conf}"
GRAVITINO_BIN="${GRAVITINO_BIN:-${GRAVITINO_HOME}/bin/gravitino.sh}"
GRAVITINO_URI="${GRAVITINO_URI:-http://127.0.0.1:8090}"
GRAVITINO_HOST="${GRAVITINO_HOST:-0.0.0.0}"
METALAKE_NAME="${METALAKE_NAME:-test}"

ICEBERG_REST_HOST="${ICEBERG_REST_HOST:-0.0.0.0}"
ICEBERG_REST_PORT="${ICEBERG_REST_PORT:-9001}"
ICEBERG_REST_URI="${ICEBERG_REST_URI:-http://127.0.0.1:${ICEBERG_REST_PORT}/iceberg/}"
ICEBERG_REST_HEALTH_URI="${ICEBERG_REST_HEALTH_URI:-http://127.0.0.1:${ICEBERG_REST_PORT}/iceberg/v1/config}"
ICEBERG_REST_CATALOG="${ICEBERG_REST_CATALOG:-iceberg}"

LANCE_REST_HOST="${LANCE_REST_HOST:-0.0.0.0}"
LANCE_REST_PORT="${LANCE_REST_PORT:-9101}"
LANCE_REST_URI="${LANCE_REST_URI:-http://127.0.0.1:${LANCE_REST_PORT}/lance}"
LANCE_REST_CATALOG="${LANCE_REST_CATALOG:-lance_catalog}"

ICEBERG_JDBC_URI="${ICEBERG_JDBC_URI:-jdbc:h2:file:${GRAVITINO_HOME}/data/iceberg_jdbc;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE}"
GRAVITINO_ENTITY_STORE_URI="${GRAVITINO_ENTITY_STORE_URI:-jdbc:h2:file:${GRAVITINO_HOME}/data/gravitino_jdbc;MODE=MySQL;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE}"
ICEBERG_WAREHOUSE="${ICEBERG_WAREHOUSE:-s3://contacts/raw/iceberg}"
LANCE_LOCATION="${LANCE_LOCATION:-s3://contacts/raw/lance}"
MINIO_ENDPOINT="${MINIO_ENDPOINT:-http://127.0.0.1:9000}"
MINIO_REGION="${MINIO_REGION:-us-east-1}"
MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY:-minioadmin}"
MINIO_SECRET_KEY="${MINIO_SECRET_KEY:-minioadmin}"

GRAVITINO_ACCEPT_HEADER="Accept: application/vnd.gravitino.v1+json"
JSON_HEADER="Content-Type: application/json"

log() {
  printf '[bootstrap] %s\n' "$*"
}

fail() {
  printf '[bootstrap] ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"
}

require_path() {
  local path="$1"
  [[ -e "${path}" ]] || fail "Required path not found: ${path}"
}

reset_iceberg_jdbc_store() {
  local deleted=false
  local jdbc_store_file

  for jdbc_store_file in "${GRAVITINO_HOME}"/data/iceberg_jdbc*; do
    if [[ -e "${jdbc_store_file}" ]]; then
      rm -f "${jdbc_store_file}"
      deleted=true
    fi
  done

  if [[ "${deleted}" == "true" ]]; then
    log "Reset Iceberg JDBC metadata store under ${GRAVITINO_HOME}/data"
  fi
}

render_gravitino_conf() {
  cat <<EOF
#
# Generated by scripts/demo/bootstrap_gravitino_lakehouse.sh
#
gravitino.server.shutdown.timeout = 3000

gravitino.server.webserver.host = ${GRAVITINO_HOST}
gravitino.server.webserver.httpPort = 8090
gravitino.server.webserver.minThreads = 24
gravitino.server.webserver.maxThreads = 200
gravitino.server.webserver.stopTimeout = 30000
gravitino.server.webserver.idleTimeout = 30000
gravitino.server.webserver.threadPoolWorkQueueSize = 100
gravitino.server.webserver.requestHeaderSize = 131072
gravitino.server.webserver.responseHeaderSize = 131072

gravitino.entity.store = relational
gravitino.entity.store.relational = JDBCBackend
gravitino.entity.store.relational.jdbcUrl = ${GRAVITINO_ENTITY_STORE_URI}
gravitino.entity.store.relational.jdbcDriver = org.h2.Driver
gravitino.entity.store.relational.jdbcUser = gravitino
gravitino.entity.store.relational.jdbcPassword = gravitino

gravitino.catalog.cache.evictionIntervalMs = 3600000
gravitino.cache.enabled = true
gravitino.cache.maxEntries = 10000
gravitino.cache.expireTimeInMs = 3600000
gravitino.cache.enableStats = false
gravitino.cache.enableWeigher = true
gravitino.cache.implementation = caffeine

gravitino.authorization.enable = false
gravitino.server.visibleConfigs = gravitino.authorization.serviceAdmins
gravitino.authorization.serviceAdmins = anonymous

gravitino.auxService.names = iceberg-rest,lance-rest

gravitino.iceberg-rest.classpath = iceberg-rest-server/libs, iceberg-rest-server/conf
gravitino.iceberg-rest.host = ${ICEBERG_REST_HOST}
gravitino.iceberg-rest.httpPort = ${ICEBERG_REST_PORT}
gravitino.iceberg-rest.catalog-config-provider = dynamic-config-provider
gravitino.iceberg-rest.gravitino-metalake = ${METALAKE_NAME}
gravitino.iceberg-rest.default-catalog-name = ${ICEBERG_REST_CATALOG}
gravitino.iceberg-rest.io-impl = org.apache.iceberg.aws.s3.S3FileIO
gravitino.iceberg-rest.credential-providers = s3-secret-key
gravitino.iceberg-rest.s3-endpoint = ${MINIO_ENDPOINT}
gravitino.iceberg-rest.s3-region = ${MINIO_REGION}
gravitino.iceberg-rest.s3-access-key-id = ${MINIO_ACCESS_KEY}
gravitino.iceberg-rest.s3-secret-access-key = ${MINIO_SECRET_KEY}
gravitino.iceberg-rest.s3-path-style-access = true

gravitino.lance-rest.classpath = lance-rest-server/libs
gravitino.lance-rest.host = ${LANCE_REST_HOST}
gravitino.lance-rest.httpPort = ${LANCE_REST_PORT}
gravitino.lance-rest.namespace-backend = gravitino
gravitino.lance-rest.gravitino-uri = ${GRAVITINO_URI}
gravitino.lance-rest.gravitino-metalake = ${METALAKE_NAME}
EOF
}

write_gravitino_conf() {
  local tmp_file backup_file

  mkdir -p "$(dirname "${GRAVITINO_CONF_FILE}")" "${GRAVITINO_HOME}/data"
  tmp_file="$(mktemp)"
  backup_file="${GRAVITINO_CONF_FILE}.bak.$(date +%Y%m%d%H%M%S)"

  render_gravitino_conf > "${tmp_file}"
  if [[ -f "${GRAVITINO_CONF_FILE}" ]]; then
    cp "${GRAVITINO_CONF_FILE}" "${backup_file}"
    log "Backed up existing config to ${backup_file}"
  fi
  mv "${tmp_file}" "${GRAVITINO_CONF_FILE}"
  log "Wrote ${GRAVITINO_CONF_FILE}"
}

http_status() {
  local method="$1"
  local url="$2"
  local data="${3:-}"
  local response_file

  response_file="$(mktemp)"
  if [[ -n "${data}" ]]; then
    curl -sS -X "${method}" \
      -H "${GRAVITINO_ACCEPT_HEADER}" \
      -H "${JSON_HEADER}" \
      -d "${data}" \
      -o "${response_file}" \
      -w '%{http_code}' \
      "${url}"
  else
    curl -sS -X "${method}" \
      -H "${GRAVITINO_ACCEPT_HEADER}" \
      -H "${JSON_HEADER}" \
      -o "${response_file}" \
      -w '%{http_code}' \
      "${url}"
  fi
  rm -f "${response_file}"
}

wait_for_url() {
  local url="$1"
  local attempts="${2:-40}"
  local sleep_seconds="${3:-3}"
  local status=""
  local attempt=1

  while (( attempt <= attempts )); do
    status="$(curl -sS -o /dev/null -w '%{http_code}' "${url}" || true)"
    if [[ "${status}" =~ ^[1-4][0-9][0-9]$ ]]; then
      log "Health check passed for ${url} (HTTP ${status})"
      return 0
    fi
    sleep "${sleep_seconds}"
    attempt=$((attempt + 1))
  done

  fail "Health check failed for ${url}, last HTTP status: ${status:-n/a}"
}

ensure_metalake() {
  local url="${GRAVITINO_URI}/api/metalakes/${METALAKE_NAME}"
  local status

  status="$(http_status GET "${url}")"
  if [[ "${status}" == "200" ]]; then
    log "Metalake ${METALAKE_NAME} already exists"
    return 0
  fi

  status="$(
    http_status \
      POST \
      "${GRAVITINO_URI}/api/metalakes" \
      "{\"name\":\"${METALAKE_NAME}\",\"comment\":\"Demo metalake for Spark + Iceberg REST + Lance REST\"}"
  )"
  [[ "${status}" == "200" ]] || fail "Create metalake failed with HTTP ${status}"
  log "Created metalake ${METALAKE_NAME}"
}

ensure_catalog() {
  local catalog_name="$1"
  local payload="$2"
  local status
  local url="${GRAVITINO_URI}/api/metalakes/${METALAKE_NAME}/catalogs/${catalog_name}"

  status="$(http_status GET "${url}")"
  if [[ "${status}" == "200" ]]; then
    log "Catalog ${catalog_name} already exists"
    return 0
  fi

  status="$(http_status POST "${GRAVITINO_URI}/api/metalakes/${METALAKE_NAME}/catalogs" "${payload}")"
  [[ "${status}" == "200" ]] || fail "Create catalog ${catalog_name} failed with HTTP ${status}"
  log "Created catalog ${catalog_name}"
}

ensure_lance_catalog() {
  ensure_catalog \
    "${LANCE_REST_CATALOG}" \
    "$(cat <<EOF
{"name":"${LANCE_REST_CATALOG}","type":"RELATIONAL","comment":"Lance catalog for local REST demo","provider":"lakehouse-generic","properties":{"location":"${LANCE_LOCATION}","lance.storage.endpoint":"${MINIO_ENDPOINT}","lance.storage.allow_http":"true","lance.storage.access_key_id":"${MINIO_ACCESS_KEY}","lance.storage.secret_access_key":"${MINIO_SECRET_KEY}","lance.storage.region":"${MINIO_REGION}"}}
EOF
)"
}

ensure_iceberg_catalog() {
  ensure_catalog \
    "${ICEBERG_REST_CATALOG}" \
    "$(cat <<EOF
{"name":"${ICEBERG_REST_CATALOG}","type":"RELATIONAL","comment":"Iceberg catalog for local REST demo","provider":"lakehouse-iceberg","properties":{"catalog-backend":"jdbc","uri":"${ICEBERG_JDBC_URI}","jdbc-driver":"org.h2.Driver","jdbc-user":"gravitino","jdbc-password":"gravitino","jdbc-initialize":"true","warehouse":"${ICEBERG_WAREHOUSE}","io-impl":"org.apache.iceberg.aws.s3.S3FileIO","credential-providers":"s3-secret-key","s3-endpoint":"${MINIO_ENDPOINT}","s3-region":"${MINIO_REGION}","s3-access-key-id":"${MINIO_ACCESS_KEY}","s3-secret-access-key":"${MINIO_SECRET_KEY}","s3-path-style-access":"true"}}
EOF
)"
}

verify_catalog_listing() {
  local response

  response="$(
    curl -sS -X GET \
      -H "${GRAVITINO_ACCEPT_HEADER}" \
      -H "${JSON_HEADER}" \
      "${GRAVITINO_URI}/api/metalakes/${METALAKE_NAME}/catalogs?details=true"
  )"
  printf '%s' "${response}" | grep -q "\"name\":\"${ICEBERG_REST_CATALOG}\"" \
    || fail "Catalog listing does not contain ${ICEBERG_REST_CATALOG}"
  printf '%s' "${response}" | grep -q "\"name\":\"${LANCE_REST_CATALOG}\"" \
    || fail "Catalog listing does not contain ${LANCE_REST_CATALOG}"
  log "Catalog listing contains ${ICEBERG_REST_CATALOG} and ${LANCE_REST_CATALOG}"
}

main() {
  require_command curl
  require_command cp
  require_command grep
  require_command rm
  require_path "${GRAVITINO_HOME}"
  require_path "${GRAVITINO_BIN}"

  write_gravitino_conf
  reset_iceberg_jdbc_store

  log "Restarting Gravitino from ${GRAVITINO_BIN}"
  "${GRAVITINO_BIN}" restart

  wait_for_url "${GRAVITINO_URI}/api/metalakes"
  wait_for_url "${ICEBERG_REST_HEALTH_URI}"
  wait_for_url "${LANCE_REST_URI}"

  ensure_metalake
  ensure_iceberg_catalog
  ensure_lance_catalog

  wait_for_url "${GRAVITINO_URI}/api/metalakes/${METALAKE_NAME}"
  verify_catalog_listing

  log "Bootstrap completed"
  log "Verified endpoints:"
  log "  ${GRAVITINO_URI}/api/metalakes"
  log "  ${ICEBERG_REST_HEALTH_URI}"
  log "  ${LANCE_REST_URI}"
}

main "$@"
