//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

== Download

Be sure to verify your downloads by these https://www.apache.org/info/verification[procedures] using these https://www.apache.org/dist/incubator/training/[KEYS] for any Apache release.

== Current Releases

=== Apache Way

[#release-navigating-ASF-incubation-1.0]
===== Navigating the ASF Incubation Process 1.0 

An overview of how to navigate the ASF incubating process from start to finish.

It can seem like a daunting task to bring a new open source project into the world. The Apache Software Foundation incubator can help you! Getting into the incubator and surviving incubation is straight forward when you know what to do and how to do it. This talk gives an overview of the ASF incubation process, the pitfalls to watch out for, and how projects become successful. It also gives an overview of the incubator PMC, how to interact with other podlings and make your mark on the ecosystem and finally how to make it as a top-level project at the Apache Software Foundation. It also goes over some the challenges that your project may face along the path to graduation.

https://www.apache.org/dyn/closer.lua/incubator/training/ApacheWay/NavigatingASFIncubation/1.0/apache-training-navigating-ASF-incubation-1.0-incubating.tar.gz[source release] [ https://www.apache.org/dist/incubator/training/ApacheWay/NavigatingASFIncubation/1.0/apache-training-navigating-ASF-incubation-1.0-incubating.tar.gz.sha512[SHA512] ] [ https://www.apache.org/dist/incubator/training/ApacheWay/NavigatingASFIncubation/1.0/apache-training-navigating-ASF-incubation-1.0-incubating.tar.gz.asc[ASC] ]
