/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.gravitino.iceberg.service.cleanup.mapper.provider.base;

import static org.apache.gravitino.iceberg.service.cleanup.mapper.IcebergCleanupJobMapper.TABLE_NAME;

import org.apache.gravitino.iceberg.service.cleanup.po.IcebergCleanupJobPO;
import org.apache.ibatis.annotations.Param;

/**
 * Portable SQL for {@code iceberg_cleanup_job}, shared by all supported JDBC backends. The
 * statements use parameterized SQL with the row id and all timestamps generated by the application
 * (not the database), so this base provider serves MySQL, H2, and PostgreSQL alike. A backend that
 * ever needs a divergent statement can subclass this and override only the affected methods.
 */
public class IcebergCleanupJobBaseSQLProvider {

  /**
   * @param po the job row to insert
   * @return the INSERT statement
   */
  public String insertCleanupJob(@Param("po") IcebergCleanupJobPO po) {
    return "INSERT INTO "
        + TABLE_NAME
        + " (id, catalog_id, namespace, table_name, metadata_location,"
        + " file_io_impl, file_io_props, state, attempts, last_error, heartbeat_at, created_by,"
        + " updated_at) VALUES (#{po.id}, #{po.catalogId}, #{po.namespace},"
        + " #{po.tableName}, #{po.metadataLocation}, #{po.fileIOImpl}, #{po.fileIOProps},"
        + " #{po.state}, #{po.attempts}, #{po.lastError}, #{po.heartbeatAt}, #{po.createdBy},"
        + " #{po.updatedAt})";
  }

  /**
   * @param heartbeatExpiry heartbeats older than this make a RUNNING row reclaimable
   * @param window max candidate rows to return
   * @return the candidate-window SELECT statement
   */
  public String selectCandidateJobs(
      @Param("heartbeatExpiry") long heartbeatExpiry, @Param("window") int window) {
    // A candidate row is PENDING, or RUNNING whose worker has gone silent. heartbeat_at is
    // NOT NULL (it defaults to 0 and markRunning always writes the current time), so the
    // staleness test is a plain comparison with no NULL branch and no three-valued-logic
    // trap, which also keeps the predicate index-friendly. Full rows are returned so a winning
    // claimer can build the job directly: the columns the job needs are immutable after enqueue,
    // so the pre-claim snapshot stays accurate without a re-read.
    return "SELECT id, catalog_id AS catalogId, namespace,"
        + " table_name AS tableName, metadata_location AS metadataLocation,"
        + " file_io_impl AS fileIOImpl, file_io_props AS fileIOProps, state, attempts,"
        + " last_error AS lastError, heartbeat_at AS heartbeatAt, created_by AS createdBy,"
        + " updated_at AS updatedAt FROM "
        + TABLE_NAME
        + " WHERE state = 'PENDING'"
        + " OR (state = 'RUNNING' AND heartbeat_at < #{heartbeatExpiry})"
        + " ORDER BY updated_at LIMIT #{window}";
  }

  /**
   * @param id job id
   * @param now claim timestamp, written as state change and initial heartbeat
   * @param heartbeatExpiry heartbeats older than this make a RUNNING row reclaimable
   * @return the claim UPDATE statement
   */
  public String markRunning(
      @Param("id") long id,
      @Param("now") long now,
      @Param("heartbeatExpiry") long heartbeatExpiry) {
    return "UPDATE "
        + TABLE_NAME
        + " SET state = 'RUNNING', heartbeat_at = #{now}, updated_at = #{now}"
        + " WHERE id = #{id} AND (state = 'PENDING'"
        + " OR (state = 'RUNNING' AND heartbeat_at < #{heartbeatExpiry}))";
  }

  /**
   * @param id job id
   * @param state terminal state to set (SUCCEEDED or FAILED)
   * @param reason failure reason, or {@code null} for success
   * @param now state-change timestamp
   * @param heartbeat the caller's owned heartbeat value (compare-and-swap ownership key)
   * @return the terminal-transition UPDATE statement
   */
  public String markFinished(
      @Param("id") long id,
      @Param("state") String state,
      @Param("reason") String reason,
      @Param("now") long now,
      @Param("heartbeat") long heartbeat) {
    // Shared transition to a final state: SUCCEEDED (reason null) or FAILED (reason set). The
    // heartbeat_at predicate checks ownership: a reclaimed worker no longer matches it.
    return "UPDATE "
        + TABLE_NAME
        + " SET state = #{state}, last_error = #{reason}, heartbeat_at = 0,"
        + " updated_at = #{now}"
        + " WHERE id = #{id} AND state = 'RUNNING' AND heartbeat_at = #{heartbeat}";
  }

  /**
   * @param id job id
   * @param reason failure reason
   * @param maxAttempts attempt ceiling past which the job is FAILED
   * @param now state-change timestamp
   * @param heartbeat the caller's owned heartbeat value (compare-and-swap ownership key)
   * @return the transient-failure UPDATE statement
   */
  public String recordFailure(
      @Param("id") long id,
      @Param("reason") String reason,
      @Param("maxAttempts") int maxAttempts,
      @Param("now") long now,
      @Param("heartbeat") long heartbeat) {
    // The state CASE must observe the pre-increment attempts value, so it MUST precede
    // "attempts = attempts + 1" in the SET list. MySQL evaluates SET assignments left to
    // right and later clauses see already-updated columns; if the increment came first the
    // CASE would compare attempts + 2 and fail one attempt early. H2 and PostgreSQL evaluate
    // every right-hand side against the original row, so state-first is correct there too,
    // keeping this statement portable across all backends. The heartbeat_at predicate checks
    // ownership (see markFinished).
    return "UPDATE "
        + TABLE_NAME
        + " SET state = CASE WHEN attempts + 1 >= #{maxAttempts} THEN 'FAILED' ELSE 'PENDING' END,"
        + " attempts = attempts + 1, last_error = #{reason},"
        + " heartbeat_at = 0, updated_at = #{now}"
        + " WHERE id = #{id} AND state = 'RUNNING' AND heartbeat_at = #{heartbeat}";
  }

  /**
   * @param id job id
   * @param lastHeartbeat previous heartbeat value the caller wrote (compare-and-swap key)
   * @param now new heartbeat value
   * @return the heartbeat UPDATE statement
   */
  public String heartbeat(
      @Param("id") long id, @Param("lastHeartbeat") long lastHeartbeat, @Param("now") long now) {
    return "UPDATE "
        + TABLE_NAME
        + " SET heartbeat_at = #{now}, updated_at = #{now}"
        + " WHERE id = #{id} AND state = 'RUNNING' AND heartbeat_at = #{lastHeartbeat}";
  }

  /**
   * @param catalogId globally unique id of the owning catalog
   * @param namespace table namespace
   * @param table table name
   * @return the unfinished-job lookup SELECT statement
   */
  public String selectUnfinishedJobId(
      @Param("catalogId") long catalogId,
      @Param("namespace") String namespace,
      @Param("table") String table) {
    // catalog_id is globally unique (catalog_meta's primary key), so it identifies the catalog
    // without scoping by metalake, and it is stable across catalog rename unlike a name.
    return "SELECT id FROM "
        + TABLE_NAME
        + " WHERE catalog_id = #{catalogId}"
        + " AND namespace = #{namespace} AND table_name = #{table}"
        + " AND state IN ('PENDING', 'RUNNING') LIMIT 1";
  }

  /**
   * @param legacyTimeline cutoff; finished rows updated before this are deleted
   * @return the cleanup DELETE statement
   */
  public String deleteFinishedJobsByLegacyTimeline(@Param("legacyTimeline") long legacyTimeline) {
    return "DELETE FROM "
        + TABLE_NAME
        + " WHERE state IN ('SUCCEEDED', 'FAILED') AND updated_at < #{legacyTimeline}";
  }

  /**
   * @param id job id
   * @return the state SELECT statement
   */
  public String selectState(@Param("id") long id) {
    return "SELECT state FROM " + TABLE_NAME + " WHERE id = #{id}";
  }
}
