--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file--
--  distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"). You may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--  http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

ALTER TABLE view_meta
    ADD COLUMN IF NOT EXISTS audit_info TEXT NOT NULL DEFAULT '{}';

ALTER TABLE view_meta
    ALTER COLUMN audit_info DROP DEFAULT;

COMMENT ON COLUMN view_meta.audit_info IS 'view audit info';

CREATE TABLE IF NOT EXISTS view_version_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    metalake_id BIGINT NOT NULL,
    catalog_id BIGINT NOT NULL,
    schema_id BIGINT NOT NULL,
    view_id BIGINT NOT NULL,
    version INT NOT NULL,
    view_comment TEXT,
    columns TEXT NOT NULL,
    properties TEXT,
    security_mode VARCHAR(32) NOT NULL DEFAULT 'DEFINER',
    representations TEXT NOT NULL,
    audit_info TEXT NOT NULL,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (view_id, version, deleted_at)
);

CREATE INDEX IF NOT EXISTS view_version_info_idx_metalake_id ON view_version_info (metalake_id);
CREATE INDEX IF NOT EXISTS view_version_info_idx_catalog_id ON view_version_info (catalog_id);
CREATE INDEX IF NOT EXISTS view_version_info_idx_schema_id ON view_version_info (schema_id);
COMMENT ON TABLE view_version_info IS 'view version info';

COMMENT ON COLUMN view_version_info.id IS 'auto increment id';
COMMENT ON COLUMN view_version_info.metalake_id IS 'metalake id';
COMMENT ON COLUMN view_version_info.catalog_id IS 'catalog id';
COMMENT ON COLUMN view_version_info.schema_id IS 'schema id';
COMMENT ON COLUMN view_version_info.view_id IS 'view id';
COMMENT ON COLUMN view_version_info.version IS 'view version';
COMMENT ON COLUMN view_version_info.view_comment IS 'view version comment';
COMMENT ON COLUMN view_version_info.columns IS 'view columns snapshot (JSON)';
COMMENT ON COLUMN view_version_info.properties IS 'view properties (JSON)';
COMMENT ON COLUMN view_version_info.security_mode IS 'DEFINER or INVOKER';
COMMENT ON COLUMN view_version_info.representations IS 'view representations (JSON array)';
COMMENT ON COLUMN view_version_info.audit_info IS 'view version audit info';
COMMENT ON COLUMN view_version_info.deleted_at IS 'view version deleted at';
