--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--  http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

ALTER TABLE user_meta ADD COLUMN IF NOT EXISTS external_id VARCHAR(256) DEFAULT NULL;
ALTER TABLE user_meta ADD COLUMN IF NOT EXISTS enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE group_meta ADD COLUMN IF NOT EXISTS external_id VARCHAR(256) DEFAULT NULL;

COMMENT ON COLUMN user_meta.external_id IS 'external id';
COMMENT ON COLUMN user_meta.enabled IS 'whether the user is enabled, 0 is disabled, 1 is enabled';
COMMENT ON COLUMN group_meta.external_id IS 'external id';

CREATE UNIQUE INDEX IF NOT EXISTS uk_mid_ueid_del ON user_meta (metalake_id, external_id, deleted_at);
CREATE UNIQUE INDEX IF NOT EXISTS uk_mid_geid_del ON group_meta (metalake_id, external_id, deleted_at);

CREATE TABLE IF NOT EXISTS user_group_rel (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    audit_info TEXT NOT NULL,
    current_version INT NOT NULL DEFAULT 1,
    last_version INT NOT NULL DEFAULT 1,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (user_id, group_id, deleted_at)
);

CREATE INDEX IF NOT EXISTS user_group_rel_idx_user_id ON user_group_rel (user_id);
COMMENT ON TABLE user_group_rel IS 'user group relation metadata';

COMMENT ON COLUMN user_group_rel.id IS 'auto increment id';
COMMENT ON COLUMN user_group_rel.user_id IS 'user id';
COMMENT ON COLUMN user_group_rel.group_id IS 'group id';
COMMENT ON COLUMN user_group_rel.audit_info IS 'relation audit info';
COMMENT ON COLUMN user_group_rel.current_version IS 'relation current version';
COMMENT ON COLUMN user_group_rel.last_version IS 'relation last version';
COMMENT ON COLUMN user_group_rel.deleted_at IS 'relation deleted at';

CREATE TABLE IF NOT EXISTS scim_token (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    metalake_id BIGINT NOT NULL,
    token_name VARCHAR(256) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at BIGINT NOT NULL DEFAULT 0,
    audit_info TEXT NOT NULL,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (metalake_id, token_name, deleted_at)
);

CREATE INDEX IF NOT EXISTS scim_token_idx_token_hash ON scim_token (token_hash);
COMMENT ON TABLE scim_token IS 'scim token metadata';

COMMENT ON COLUMN scim_token.id IS 'auto increment id';
COMMENT ON COLUMN scim_token.metalake_id IS 'metalake id';
COMMENT ON COLUMN scim_token.token_name IS 'scim token name';
COMMENT ON COLUMN scim_token.token_hash IS 'SHA-256 hex digest of scim token value';
COMMENT ON COLUMN scim_token.expires_at IS 'token expiry time in ms, 0 means never expires';
COMMENT ON COLUMN scim_token.audit_info IS 'scim token audit info';
COMMENT ON COLUMN scim_token.deleted_at IS 'token deleted at';
