--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"). You may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--  http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

ALTER TABLE user_meta  ADD COLUMN IF NOT EXISTS updated_at BIGINT NOT NULL DEFAULT 0;
ALTER TABLE role_meta ADD COLUMN IF NOT EXISTS updated_at BIGINT NOT NULL DEFAULT 0;
ALTER TABLE owner_meta ADD COLUMN IF NOT EXISTS updated_at BIGINT NOT NULL DEFAULT 0;
COMMENT ON COLUMN user_meta.updated_at IS 'updated at';
COMMENT ON COLUMN role_meta.updated_at IS 'updated at';
COMMENT ON COLUMN owner_meta.updated_at IS 'updated at';

CREATE INDEX IF NOT EXISTS idx_user_meta_name_del_upd ON user_meta (metalake_id, user_name, deleted_at, updated_at);
CREATE INDEX IF NOT EXISTS idx_role_meta_del_upd ON role_meta (role_id, deleted_at, updated_at);
CREATE INDEX IF NOT EXISTS idx_owner_meta_del_upd_obj ON owner_meta (deleted_at, updated_at, metadata_object_id);

CREATE TABLE IF NOT EXISTS entity_change_log (
    id BIGSERIAL PRIMARY KEY,
    metalake_name VARCHAR(128) NOT NULL,
    entity_type VARCHAR(32) NOT NULL,
    entity_full_name VARCHAR(512) NOT NULL,
    -- Operate type code: 1=ALTER, 2=DROP, 3=INSERT. Codes are stable and never re-used.
    operate_type SMALLINT NOT NULL,
    created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ecl_created_at ON entity_change_log(created_at);
COMMENT ON TABLE entity_change_log IS 'Append-only log of entity structural changes for targeted metadataIdCache invalidation';
COMMENT ON COLUMN entity_change_log.id IS 'auto increment id';
COMMENT ON COLUMN entity_change_log.metalake_name IS 'metalake name';
COMMENT ON COLUMN entity_change_log.entity_type IS 'METALAKE | CATALOG | SCHEMA | TABLE | FILESET | TOPIC | MODEL | VIEW';
COMMENT ON COLUMN entity_change_log.entity_full_name IS 'Dot-separated full name of the affected entity. For ALTER, stores the old name. For DROP, stores the entity name.';
COMMENT ON COLUMN entity_change_log.operate_type IS 'Operate type code: 1=ALTER, 2=DROP, 3=INSERT. Codes are stable and never re-used.';
COMMENT ON COLUMN entity_change_log.created_at IS 'timestamp of the change in millis';

ALTER TABLE view_meta
    ADD COLUMN IF NOT EXISTS audit_info TEXT NOT NULL DEFAULT '{}';

ALTER TABLE view_meta
    ALTER COLUMN audit_info DROP DEFAULT;

COMMENT ON COLUMN view_meta.audit_info IS 'view audit info';

CREATE TABLE IF NOT EXISTS view_version_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    metalake_id BIGINT NOT NULL,
    catalog_id BIGINT NOT NULL,
    schema_id BIGINT NOT NULL,
    view_id BIGINT NOT NULL,
    version INT NOT NULL,
    view_comment TEXT,
    columns TEXT NOT NULL,
    properties TEXT,
    default_catalog VARCHAR(128),
    default_schema VARCHAR(128),
    representations TEXT NOT NULL,
    audit_info TEXT NOT NULL,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (view_id, version, deleted_at)
);

CREATE INDEX IF NOT EXISTS view_version_info_idx_metalake_id ON view_version_info (metalake_id);
CREATE INDEX IF NOT EXISTS view_version_info_idx_catalog_id ON view_version_info (catalog_id);
CREATE INDEX IF NOT EXISTS view_version_info_idx_schema_id ON view_version_info (schema_id);
COMMENT ON TABLE view_version_info IS 'view version info';

COMMENT ON COLUMN view_version_info.id IS 'auto increment id';
COMMENT ON COLUMN view_version_info.metalake_id IS 'metalake id';
COMMENT ON COLUMN view_version_info.catalog_id IS 'catalog id';
COMMENT ON COLUMN view_version_info.schema_id IS 'schema id';
COMMENT ON COLUMN view_version_info.view_id IS 'view id';
COMMENT ON COLUMN view_version_info.version IS 'view version';
COMMENT ON COLUMN view_version_info.view_comment IS 'view version comment';
COMMENT ON COLUMN view_version_info.columns IS 'view columns snapshot (JSON)';
COMMENT ON COLUMN view_version_info.properties IS 'view properties (JSON)';
COMMENT ON COLUMN view_version_info.default_catalog IS 'default catalog for view SQL resolution';
COMMENT ON COLUMN view_version_info.default_schema IS 'default schema for view SQL resolution';
COMMENT ON COLUMN view_version_info.representations IS 'view representations (JSON array)';
COMMENT ON COLUMN view_version_info.audit_info IS 'view version audit info';
COMMENT ON COLUMN view_version_info.deleted_at IS 'view version deleted at';
