--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file--
--  distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"). You may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--  http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

ALTER TABLE view_meta
    ADD COLUMN IF NOT EXISTS audit_info TEXT NOT NULL DEFAULT '{}';

ALTER TABLE view_meta
    ALTER COLUMN audit_info DROP DEFAULT;

COMMENT ON COLUMN view_meta.audit_info IS 'view audit info';

CREATE TABLE IF NOT EXISTS view_version_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    metalake_id BIGINT NOT NULL,
    catalog_id BIGINT NOT NULL,
    schema_id BIGINT NOT NULL,
    view_id BIGINT NOT NULL,
    version INT NOT NULL,
    view_comment TEXT,
    columns TEXT NOT NULL,
    properties TEXT,
    default_catalog VARCHAR(128),
    default_schema VARCHAR(128),
    representations TEXT NOT NULL,
    audit_info TEXT NOT NULL,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (view_id, version, deleted_at)
);

CREATE INDEX IF NOT EXISTS view_version_info_idx_metalake_id ON view_version_info (metalake_id);
CREATE INDEX IF NOT EXISTS view_version_info_idx_catalog_id ON view_version_info (catalog_id);
CREATE INDEX IF NOT EXISTS view_version_info_idx_schema_id ON view_version_info (schema_id);
COMMENT ON TABLE view_version_info IS 'view version info';

COMMENT ON COLUMN view_version_info.id IS 'auto increment id';
COMMENT ON COLUMN view_version_info.metalake_id IS 'metalake id';
COMMENT ON COLUMN view_version_info.catalog_id IS 'catalog id';
COMMENT ON COLUMN view_version_info.schema_id IS 'schema id';
COMMENT ON COLUMN view_version_info.view_id IS 'view id';
COMMENT ON COLUMN view_version_info.version IS 'view version';
COMMENT ON COLUMN view_version_info.view_comment IS 'view version comment';
COMMENT ON COLUMN view_version_info.columns IS 'view columns snapshot (JSON)';
COMMENT ON COLUMN view_version_info.properties IS 'view properties (JSON)';
COMMENT ON COLUMN view_version_info.default_catalog IS 'default catalog for view SQL resolution';
COMMENT ON COLUMN view_version_info.default_schema IS 'default schema for view SQL resolution';
COMMENT ON COLUMN view_version_info.representations IS 'view representations (JSON array)';
COMMENT ON COLUMN view_version_info.audit_info IS 'view version audit info';
COMMENT ON COLUMN view_version_info.deleted_at IS 'view version deleted at';

CREATE TABLE IF NOT EXISTS idp_user_meta (
    user_id BIGINT NOT NULL,
    user_name VARCHAR(128) NOT NULL,
    password_hash VARCHAR(1024) NOT NULL,
    audit_info TEXT NOT NULL,
    current_version INT NOT NULL DEFAULT 1,
    last_version INT NOT NULL DEFAULT 1,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id),
    UNIQUE (user_name, deleted_at)
);
COMMENT ON TABLE idp_user_meta IS 'local IdP user metadata';

COMMENT ON COLUMN idp_user_meta.user_id IS 'idp user id';
COMMENT ON COLUMN idp_user_meta.user_name IS 'idp username';
COMMENT ON COLUMN idp_user_meta.password_hash IS 'idp user password hash';
COMMENT ON COLUMN idp_user_meta.audit_info IS 'idp user audit info';
COMMENT ON COLUMN idp_user_meta.current_version IS 'idp user current version';
COMMENT ON COLUMN idp_user_meta.last_version IS 'idp user last version';
COMMENT ON COLUMN idp_user_meta.deleted_at IS 'idp user deleted at';

CREATE TABLE IF NOT EXISTS idp_group_meta (
    group_id BIGINT NOT NULL,
    group_name VARCHAR(128) NOT NULL,
    audit_info TEXT NOT NULL,
    current_version INT NOT NULL DEFAULT 1,
    last_version INT NOT NULL DEFAULT 1,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (group_id),
    UNIQUE (group_name, deleted_at)
);
COMMENT ON TABLE idp_group_meta IS 'local IdP group metadata';

COMMENT ON COLUMN idp_group_meta.group_id IS 'idp group id';
COMMENT ON COLUMN idp_group_meta.group_name IS 'idp group name';
COMMENT ON COLUMN idp_group_meta.audit_info IS 'idp group audit info';
COMMENT ON COLUMN idp_group_meta.current_version IS 'idp group current version';
COMMENT ON COLUMN idp_group_meta.last_version IS 'idp group last version';
COMMENT ON COLUMN idp_group_meta.deleted_at IS 'idp group deleted at';

CREATE TABLE IF NOT EXISTS idp_group_user_rel (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    audit_info TEXT NOT NULL,
    current_version INT NOT NULL DEFAULT 1,
    last_version INT NOT NULL DEFAULT 1,
    deleted_at BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE (group_id, user_id, deleted_at)
);
CREATE INDEX IF NOT EXISTS idp_group_user_rel_idx_user_id ON idp_group_user_rel (user_id);
COMMENT ON TABLE idp_group_user_rel IS 'local IdP group user relation';

COMMENT ON COLUMN idp_group_user_rel.id IS 'auto increment id';
COMMENT ON COLUMN idp_group_user_rel.group_id IS 'idp group id';
COMMENT ON COLUMN idp_group_user_rel.user_id IS 'idp user id';
COMMENT ON COLUMN idp_group_user_rel.audit_info IS 'idp group user relation audit info';
COMMENT ON COLUMN idp_group_user_rel.current_version IS 'idp relation current version';
COMMENT ON COLUMN idp_group_user_rel.last_version IS 'idp relation last version';
COMMENT ON COLUMN idp_group_user_rel.deleted_at IS 'idp relation deleted at';
