{{- /*
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
  */}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ include "gravitino-iceberg-rest-server.namespace" . }}
  labels:
    {{- include "gravitino-iceberg-rest-server.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}

spec:
  type: {{ .Values.service.type | default "ClusterIP" }}

  # LoadBalancer specific configuration
  {{- if eq .Values.service.type "LoadBalancer" }}
  loadBalancerClass: {{ .Values.service.loadBalancerClass | default "" }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}

  # ClusterIP specific configuration
  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}

  # External IP configuration
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  # Port configuration
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

    # Extra exposed ports
  {{- if .Values.extraExposePorts }}
    - {{ tpl (toYaml .Values.extraExposePorts) . | trim }}
  {{- end }}

    # Selector for pods
  selector:
    app: {{ include "gravitino-iceberg-rest-server.name" . }}
    release: {{ .Release.Name }}