/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.gravitino.iceberg.service.cleanup;

import static org.apache.gravitino.iceberg.service.cleanup.IcebergCleanupJobMapper.TABLE_NAME;

import com.google.common.collect.ImmutableMap;
import java.util.Map;
import org.apache.gravitino.storage.relational.JDBCBackend.JDBCBackendType;
import org.apache.gravitino.storage.relational.session.SqlSessionFactoryHelper;
import org.apache.ibatis.annotations.Param;

/**
 * Supplies the SQL for {@link IcebergCleanupJobMapper}, dispatching by the entity store's
 * configured JDBC backend. The statements are written with portable, parameterized SQL (the row id
 * and all timestamps are generated by the application, not the database), so the {@link
 * BaseProvider} serves MySQL, H2, and PostgreSQL alike. A backend that ever needs a divergent
 * statement can be registered here by mapping its {@link JDBCBackendType} to a {@code BaseProvider}
 * subclass that overrides only the affected methods.
 */
public class IcebergCleanupJobSQLProviderFactory {

  private static final BaseProvider BASE_PROVIDER = new BaseProvider();

  private static final Map<JDBCBackendType, BaseProvider> PROVIDERS =
      ImmutableMap.of(
          JDBCBackendType.MYSQL, BASE_PROVIDER,
          JDBCBackendType.H2, BASE_PROVIDER,
          JDBCBackendType.POSTGRESQL, BASE_PROVIDER);

  private static BaseProvider getProvider() {
    String databaseId =
        SqlSessionFactoryHelper.getInstance()
            .getSqlSessionFactory()
            .getConfiguration()
            .getDatabaseId();
    return PROVIDERS.get(JDBCBackendType.fromString(databaseId));
  }

  public static String insertCleanupJob(@Param("po") IcebergCleanupJobPO po) {
    return getProvider().insertCleanupJob(po);
  }

  public static String selectCandidateJobIds(
      @Param("heartbeatExpiry") long heartbeatExpiry, @Param("window") int window) {
    return getProvider().selectCandidateJobIds(heartbeatExpiry, window);
  }

  public static String markRunning(
      @Param("id") long id,
      @Param("now") long now,
      @Param("heartbeatExpiry") long heartbeatExpiry) {
    return getProvider().markRunning(id, now, heartbeatExpiry);
  }

  public static String selectById(@Param("id") long id) {
    return getProvider().selectById(id);
  }

  public static String markFinished(
      @Param("id") long id,
      @Param("state") String state,
      @Param("reason") String reason,
      @Param("now") long now) {
    return getProvider().markFinished(id, state, reason, now);
  }

  public static String recordFailure(
      @Param("id") long id,
      @Param("reason") String reason,
      @Param("maxAttempts") int maxAttempts,
      @Param("now") long now) {
    return getProvider().recordFailure(id, reason, maxAttempts, now);
  }

  public static String heartbeat(
      @Param("id") long id, @Param("lastHeartbeat") long lastHeartbeat, @Param("now") long now) {
    return getProvider().heartbeat(id, lastHeartbeat, now);
  }

  public static String selectActiveJobId(
      @Param("catalog") String catalog,
      @Param("namespace") String namespace,
      @Param("table") String table) {
    return getProvider().selectActiveJobId(catalog, namespace, table);
  }

  public static String deleteFinishedJobsByLegacyTimeline(
      @Param("legacyTimeline") long legacyTimeline) {
    return getProvider().deleteFinishedJobsByLegacyTimeline(legacyTimeline);
  }

  public static String selectState(@Param("id") long id) {
    return getProvider().selectState(id);
  }

  /** Portable SQL shared by all supported JDBC backends. */
  static class BaseProvider {

    String insertCleanupJob(@Param("po") IcebergCleanupJobPO po) {
      return "INSERT INTO "
          + TABLE_NAME
          + " (id, metalake_name, catalog_name, namespace, table_name, metadata_location,"
          + " file_io_impl, file_io_props, state, attempts, last_error, heartbeat_at, created_by,"
          + " updated_at) VALUES (#{po.id}, #{po.metalakeName}, #{po.catalogName}, #{po.namespace},"
          + " #{po.tableName}, #{po.metadataLocation}, #{po.fileIOImpl}, #{po.fileIOProps},"
          + " #{po.state}, #{po.attempts}, #{po.lastError}, #{po.heartbeatAt}, #{po.createdBy},"
          + " #{po.updatedAt})";
    }

    String selectCandidateJobIds(
        @Param("heartbeatExpiry") long heartbeatExpiry, @Param("window") int window) {
      // A candidate row is PENDING, or RUNNING whose worker has gone silent. heartbeat_at is
      // NOT NULL (it defaults to 0 and markRunning always writes the current time), so the
      // staleness test is a plain comparison with no NULL branch and no three-valued-logic
      // trap, which also keeps the predicate index-friendly.
      return "SELECT id FROM "
          + TABLE_NAME
          + " WHERE state = 'PENDING'"
          + " OR (state = 'RUNNING' AND heartbeat_at < #{heartbeatExpiry})"
          + " ORDER BY updated_at LIMIT #{window}";
    }

    String markRunning(
        @Param("id") long id,
        @Param("now") long now,
        @Param("heartbeatExpiry") long heartbeatExpiry) {
      return "UPDATE "
          + TABLE_NAME
          + " SET state = 'RUNNING', heartbeat_at = #{now}, updated_at = #{now}"
          + " WHERE id = #{id} AND (state = 'PENDING'"
          + " OR (state = 'RUNNING' AND heartbeat_at < #{heartbeatExpiry}))";
    }

    String selectById(@Param("id") long id) {
      return "SELECT id, metalake_name AS metalakeName, catalog_name AS catalogName, namespace,"
          + " table_name AS tableName, metadata_location AS metadataLocation,"
          + " file_io_impl AS fileIOImpl, file_io_props AS fileIOProps, state, attempts,"
          + " last_error AS lastError, heartbeat_at AS heartbeatAt, created_by AS createdBy,"
          + " updated_at AS updatedAt FROM "
          + TABLE_NAME
          + " WHERE id = #{id}";
    }

    String markFinished(
        @Param("id") long id,
        @Param("state") String state,
        @Param("reason") String reason,
        @Param("now") long now) {
      // Shared transition to a final state: SUCCEEDED (reason null) or FAILED (reason set).
      return "UPDATE "
          + TABLE_NAME
          + " SET state = #{state}, last_error = #{reason}, heartbeat_at = 0,"
          + " updated_at = #{now} WHERE id = #{id} AND state = 'RUNNING'";
    }

    String recordFailure(
        @Param("id") long id,
        @Param("reason") String reason,
        @Param("maxAttempts") int maxAttempts,
        @Param("now") long now) {
      // The state CASE must observe the pre-increment attempts value, so it MUST precede
      // "attempts = attempts + 1" in the SET list. MySQL evaluates SET assignments left to
      // right and later clauses see already-updated columns; if the increment came first the
      // CASE would compare attempts + 2 and fail one attempt early. H2 and PostgreSQL evaluate
      // every right-hand side against the original row, so state-first is correct there too,
      // keeping this statement portable across all backends.
      return "UPDATE "
          + TABLE_NAME
          + " SET state = CASE WHEN attempts + 1 >= #{maxAttempts} THEN 'FAILED' ELSE 'PENDING' END,"
          + " attempts = attempts + 1, last_error = #{reason},"
          + " heartbeat_at = 0, updated_at = #{now} WHERE id = #{id} AND state = 'RUNNING'";
    }

    String heartbeat(
        @Param("id") long id, @Param("lastHeartbeat") long lastHeartbeat, @Param("now") long now) {
      return "UPDATE "
          + TABLE_NAME
          + " SET heartbeat_at = #{now}, updated_at = #{now}"
          + " WHERE id = #{id} AND state = 'RUNNING' AND heartbeat_at = #{lastHeartbeat}";
    }

    String selectActiveJobId(
        @Param("catalog") String catalog,
        @Param("namespace") String namespace,
        @Param("table") String table) {
      return "SELECT id FROM "
          + TABLE_NAME
          + " WHERE catalog_name = #{catalog} AND namespace = #{namespace}"
          + " AND table_name = #{table} AND state IN ('PENDING', 'RUNNING') LIMIT 1";
    }

    String deleteFinishedJobsByLegacyTimeline(@Param("legacyTimeline") long legacyTimeline) {
      return "DELETE FROM "
          + TABLE_NAME
          + " WHERE state IN ('SUCCEEDED', 'FAILED') AND updated_at < #{legacyTimeline}";
    }

    String selectState(@Param("id") long id) {
      return "SELECT state FROM " + TABLE_NAME + " WHERE id = #{id}";
    }
  }
}
