name: Build gvfs-fuse and testing

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "branch-*" ]
  pull_request:
    branches: [ "main", "branch-*" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            source_changes:
              - .github/**
              - api/**
              - bin/**
              - catalogs/hadoop/**
              - clients/filesystem-fuse/**
              - common/**
              - conf/**
              - core/**
              - dev/**
              - gradle/**
              - meta/**
              - scripts/**
              - server/**
              - server-common/**
              - build.gradle.kts
              - gradle.properties
              - gradlew
              - setting.gradle.kts
    outputs:
      source_changes: ${{ steps.filter.outputs.source_changes }}

  # Build for AMD64 architecture
  Gvfs-Build:
    needs: changes
    if: needs.changes.outputs.source_changes == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        architecture: [linux/amd64]
        java-version: [ 17 ]
    env:
      PLATFORM: ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Check required command
        run: |
          dev/ci/check_commands.sh

      - name: Build Gvfs-fuse
        run: |
           ./gradlew :clients:filesystem-fuse:build -PenableFuse=true

      - name: Integration test
        run: |
          ./gradlew build -x :clients:client-python:build -x test -x web -PjdkVersion=${{ matrix.java-version }}
          ./gradlew compileDistribution -x :clients:client-python:build -x test -x web -PjdkVersion=${{ matrix.java-version }}
          cd clients/filesystem-fuse
          make test-s3
          make test-fuse-it

      - name: Free up disk space
        run: |
          dev/ci/util_free_space.sh

      - name: Upload tests reports
        uses: actions/upload-artifact@v4
        if: ${{ (failure() && steps.integrationTest.outcome == 'failure') || contains(github.event.pull_request.labels.*.name, 'upload log') }}
        with:
          name: Gvfs-fuse integrate-test-reports-${{ matrix.java-version }}
          path: |
            clients/filesystem-fuse/target/debug/fuse.log
            distribution/package/logs/gravitino-server.out
            distribution/package/logs/gravitino-server.log

