name: New Integration Test Action

# run integration test
on:
  workflow_call:
    inputs:
      architecture:
        required: true
        description: 'Architecture of the platform'
        type: string
      java-version:
        required: true
        description: 'Java version'
        type: string
      backend:
        required: true
        description: 'Backend storage for Gravitino'
        type: string
      test-mode:
        required: true
        description: 'run on embedded or deploy mode'
        type: string

jobs:
  start-runner:
    name: JDK${{ inputs.java-version }}-${{ inputs.test-mode }}-${{ inputs.backend }}
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      PLATFORM: ${{ inputs.architecture }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Check required command
        run: |
          dev/ci/check_commands.sh

      - name: Package Gravitino
        if: ${{ inputs.test-mode == 'deploy' }}
        run: |
          ./gradlew compileDistribution -x test -PjdkVersion=${{ inputs.java-version }}

      - name: Free up disk space
        run: |
          dev/ci/util_free_space.sh

      - name: Integration Test (JDK${{ inputs.java-version }}-${{ inputs.test-mode }}-${{ inputs.backend }})
        id: integrationTest
        run: >
          ./gradlew :integration-test:test -PtestMode=${{ inputs.test-mode }} -PjdkVersion=${{ inputs.java-version }} -PjdbcBackend=${{ inputs.backend }} -PskipDockerTests=false

      - name: Upload integrate tests reports
        uses: actions/upload-artifact@v4
        if: ${{ (failure() && steps.integrationTest.outcome == 'failure') || contains(github.event.pull_request.labels.*.name, 'upload log') }}
        with:
          name: integrate-test-reports-${{ inputs.java-version }}-${{ inputs.test-mode }}-${{ inputs.backend }}
          path: |
            build/reports
            iceberg/iceberg-rest-server/build/*.log
            distribution/package/logs/*.out
            distribution/package/logs/*.log
            integration-test/**/**/*.log
            integration-test/**/**/*.tar
            distribution/**/*.log
