name: Publish Gravitino to OSSRH

on:
  # Triggers the workflow on push events only for the release branches(branch-*) and test branches(test*)
  push:
    branches: [ "branch-*", "test*" ]

jobs:
  publish-gravitino:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      SONATYPE_USER: ${{ secrets.OSSRH_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Check publish username and password
        run: |
          if [ "${SONATYPE_USER}" = "" ] || [ "${SONATYPE_PASSWORD}" = "" ]; then
            echo "Username or password is empty. Please try to set github action secret OSSRH_USERNAME and OSSRH_PASSWORD. "
            exit 1
          fi

      - name: Clean, build and publish the release(branch-*) branch
        run: ./gradlew clean build publish