name: 'Python CI'

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.8', '3.9', '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade pip
          python -m pip list
          echo ${{ github.workspace }}/clients/client-python/requirements.txt
          cat ${{ github.workspace }}/clients/client-python/requirements.txt
          python -m pip install -r ${{ github.workspace }}/clients/client-python/requirements.txt
          python -m pip list
      - name: Unit tests
        run: pytest ${{ github.workspace }}/clients/client-python/tests