name: 'Python CI'

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: [ '3.8', '3.9', '3.10', '3.11' ]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd clients/client-python
          python --version
          python -m pip install --upgrade pip
          python -m pip list
          python pip install -i requirements.txt
          python -m pip list
      - name: Unit tests
        run: pytest