name: Python Client Integration Test

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "branch-*" ]
  pull_request:
    branches: [ "main", "branch-*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Disable Git automatic maintenance
        run: git config --local maintenance.auto false
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d
        id: filter
        with:
          filters: |
            source_changes:
              - .github/**
              - api/**
              - authorizations/**
              - bin/**
              - catalogs/**
              - clients/client-python/**
              - common/**
              - conf/**
              - core/**
              - dev/**
              - gradle/**
              - iceberg/**
              - meta/**
              - scripts/**
              - server/**
              - server-common/**
              - build.gradle.kts
              - gradle.properties
              - gradlew
              - settings.gradle.kts
    outputs:
      source_changes: ${{ steps.filter.outputs.source_changes }}

  PythonIT:
    needs: changes
    if: needs.changes.outputs.source_changes == 'true'
    strategy:
      matrix:
        architecture: [linux/amd64]
        java-version: [ 17 ]
    uses: ./.github/workflows/python-integration-test-action.yml
    with:
      architecture: ${{ matrix.architecture }}
      java-version: ${{ matrix.java-version }}
