name: Trino Integration Test

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "branch-*" ]
  pull_request:
    branches: [ "main", "branch-*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            source_changes:
              - .github/**
              - api/**
              - bin/**
              - catalogs/**
              - clients/client-java/**
              - clients/client-java-runtime/**
              - common/**
              - conf/**
              - core/**
              - dev/**
              - gradle/**
              - iceberg/**
              - integration-test-common/**
              - meta/**
              - scripts/**
              - server/**
              - server-common/**
              - trino-connector/**
              - build.gradle.kts
              - gradle.properties
              - gradlew
              - setting.gradle.kts
    outputs:
      source_changes: ${{ steps.filter.outputs.source_changes }}

  # Integration test for AMD64 architecture
  TrinoIT:
    needs: changes
    if: needs.changes.outputs.source_changes == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        architecture: [linux/amd64]
        java-version: [ 17 ]
    env:
      PLATFORM: ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Check required command
        run: |
          dev/ci/check_commands.sh

      - name: Package Gravitino
        run: |
          ./gradlew compileDistribution -x test -PjdkVersion=${{ matrix.java-version }}

      - name: Free up disk space
        run: |
          dev/ci/util_free_space.sh

      - name: Trino Integration Test
        id: integrationTest
        run: |
          ./gradlew -PskipTests -PtestMode=embedded -PjdkVersion=${{ matrix.java-version }} -PskipDockerTests=false :trino-connector:integration-test:test
          ./gradlew -PskipTests -PtestMode=deploy -PjdkVersion=${{ matrix.java-version }} -PskipDockerTests=false :trino-connector:integration-test:test

      - name: Upload integrate tests reports
        uses: actions/upload-artifact@v3
        if: ${{ (failure() && steps.integrationTest.outcome == 'failure') || contains(github.event.pull_request.labels.*.name, 'upload log') }}
        with:
          name: trino-connector-integrate-test-reports-${{ matrix.java-version }}
          path: |
            build/reports
            trino-connector/integrate-test/build/*.log
            trino-connector/integrate-test/build/*.tar
            integration-test-common/build/trino-ci-container-log
            distribution/package/logs/gravitino-server.out
            distribution/package/logs/gravitino-server.log
            catalogs/**/*.log
            catalogs/**/*.tar