/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.gravitino.iceberg.service.purge;

import static org.apache.gravitino.iceberg.service.purge.IcebergPurgeJobMapper.TABLE_NAME;

import com.google.common.collect.ImmutableMap;
import java.util.Map;
import org.apache.gravitino.storage.relational.JDBCBackend.JDBCBackendType;
import org.apache.gravitino.storage.relational.session.SqlSessionFactoryHelper;
import org.apache.ibatis.annotations.Param;

/**
 * Supplies the SQL for {@link IcebergPurgeJobMapper}, dispatching by the entity store's configured
 * JDBC backend. The statements are written with portable, parameterized SQL (the row id and all
 * timestamps are generated by the application, not the database), so the {@link BaseProvider}
 * serves MySQL, H2, and PostgreSQL alike. A backend that ever needs a divergent statement can be
 * registered here by mapping its {@link JDBCBackendType} to a {@code BaseProvider} subclass that
 * overrides only the affected methods.
 */
public class IcebergPurgeJobSQLProviderFactory {

  private static final BaseProvider BASE_PROVIDER = new BaseProvider();

  private static final Map<JDBCBackendType, BaseProvider> PROVIDERS =
      ImmutableMap.of(
          JDBCBackendType.MYSQL, BASE_PROVIDER,
          JDBCBackendType.H2, BASE_PROVIDER,
          JDBCBackendType.POSTGRESQL, BASE_PROVIDER);

  private static BaseProvider getProvider() {
    String databaseId =
        SqlSessionFactoryHelper.getInstance()
            .getSqlSessionFactory()
            .getConfiguration()
            .getDatabaseId();
    return PROVIDERS.get(JDBCBackendType.fromString(databaseId));
  }

  public static String insertPurgeJob(@Param("po") IcebergPurgeJobPO po) {
    return getProvider().insertPurgeJob(po);
  }

  public static String selectClaimableIds(
      @Param("staleBefore") long staleBefore, @Param("window") int window) {
    return getProvider().selectClaimableIds(staleBefore, window);
  }

  public static String markRunning(
      @Param("id") long id, @Param("now") long now, @Param("staleBefore") long staleBefore) {
    return getProvider().markRunning(id, now, staleBefore);
  }

  public static String selectById(@Param("id") long id) {
    return getProvider().selectById(id);
  }

  public static String markSucceeded(@Param("id") long id, @Param("now") long now) {
    return getProvider().markSucceeded(id, now);
  }

  public static String markFailed(
      @Param("id") long id, @Param("reason") String reason, @Param("now") long now) {
    return getProvider().markFailed(id, reason, now);
  }

  public static String recordFailure(
      @Param("id") long id,
      @Param("reason") String reason,
      @Param("maxAttempts") int maxAttempts,
      @Param("now") long now) {
    return getProvider().recordFailure(id, reason, maxAttempts, now);
  }

  public static String heartbeat(
      @Param("id") long id, @Param("lastWritten") long lastWritten, @Param("now") long now) {
    return getProvider().heartbeat(id, lastWritten, now);
  }

  public static String selectActiveJobId(
      @Param("catalog") String catalog,
      @Param("namespace") String namespace,
      @Param("table") String table) {
    return getProvider().selectActiveJobId(catalog, namespace, table);
  }

  public static String pruneFinishedBefore(@Param("updatedBefore") long updatedBefore) {
    return getProvider().pruneFinishedBefore(updatedBefore);
  }

  public static String selectState(@Param("id") long id) {
    return getProvider().selectState(id);
  }

  /** Portable SQL shared by all supported JDBC backends. */
  static class BaseProvider {

    String insertPurgeJob(@Param("po") IcebergPurgeJobPO po) {
      return "INSERT INTO "
          + TABLE_NAME
          + " (id, metalake_name, catalog_name, namespace, table_name, metadata_location,"
          + " file_io_impl, file_io_props, state, attempts, last_error, heartbeat_at, created_by,"
          + " updated_at) VALUES (#{po.id}, #{po.metalakeName}, #{po.catalogName}, #{po.namespace},"
          + " #{po.tableName}, #{po.metadataLocation}, #{po.fileIOImpl}, #{po.fileIOProps},"
          + " #{po.state}, #{po.attempts}, #{po.lastError}, #{po.heartbeatAt}, #{po.createdBy},"
          + " #{po.updatedAt})";
    }

    String selectClaimableIds(@Param("staleBefore") long staleBefore, @Param("window") int window) {
      return "SELECT id FROM "
          + TABLE_NAME
          + " WHERE state = 'PENDING'"
          + " OR (state = 'RUNNING' AND (heartbeat_at IS NULL OR heartbeat_at < #{staleBefore}))"
          + " ORDER BY updated_at LIMIT #{window}";
    }

    String markRunning(
        @Param("id") long id, @Param("now") long now, @Param("staleBefore") long staleBefore) {
      return "UPDATE "
          + TABLE_NAME
          + " SET state = 'RUNNING', heartbeat_at = #{now}, updated_at = #{now}"
          + " WHERE id = #{id} AND (state = 'PENDING'"
          + " OR (state = 'RUNNING' AND (heartbeat_at IS NULL OR heartbeat_at < #{staleBefore})))";
    }

    String selectById(@Param("id") long id) {
      return "SELECT id, metalake_name AS metalakeName, catalog_name AS catalogName, namespace,"
          + " table_name AS tableName, metadata_location AS metadataLocation,"
          + " file_io_impl AS fileIOImpl, file_io_props AS fileIOProps, state, attempts,"
          + " last_error AS lastError, heartbeat_at AS heartbeatAt, created_by AS createdBy,"
          + " updated_at AS updatedAt FROM "
          + TABLE_NAME
          + " WHERE id = #{id}";
    }

    String markSucceeded(@Param("id") long id, @Param("now") long now) {
      return "UPDATE "
          + TABLE_NAME
          + " SET state = 'SUCCEEDED', heartbeat_at = NULL, updated_at = #{now}"
          + " WHERE id = #{id} AND state = 'RUNNING'";
    }

    String markFailed(
        @Param("id") long id, @Param("reason") String reason, @Param("now") long now) {
      return "UPDATE "
          + TABLE_NAME
          + " SET state = 'FAILED', last_error = #{reason}, heartbeat_at = NULL, updated_at = #{now}"
          + " WHERE id = #{id} AND state = 'RUNNING'";
    }

    String recordFailure(
        @Param("id") long id,
        @Param("reason") String reason,
        @Param("maxAttempts") int maxAttempts,
        @Param("now") long now) {
      // The state CASE must observe the pre-increment attempts value, so it MUST precede
      // "attempts = attempts + 1" in the SET list. MySQL evaluates SET assignments left to
      // right and later clauses see already-updated columns; if the increment came first the
      // CASE would compare attempts + 2 and fail one attempt early. H2 and PostgreSQL evaluate
      // every right-hand side against the original row, so state-first is correct there too,
      // keeping this statement portable across all backends.
      return "UPDATE "
          + TABLE_NAME
          + " SET state = CASE WHEN attempts + 1 >= #{maxAttempts} THEN 'FAILED' ELSE 'PENDING' END,"
          + " attempts = attempts + 1, last_error = #{reason},"
          + " heartbeat_at = NULL, updated_at = #{now} WHERE id = #{id} AND state = 'RUNNING'";
    }

    String heartbeat(
        @Param("id") long id, @Param("lastWritten") long lastWritten, @Param("now") long now) {
      return "UPDATE "
          + TABLE_NAME
          + " SET heartbeat_at = #{now}, updated_at = #{now}"
          + " WHERE id = #{id} AND state = 'RUNNING' AND heartbeat_at = #{lastWritten}";
    }

    String selectActiveJobId(
        @Param("catalog") String catalog,
        @Param("namespace") String namespace,
        @Param("table") String table) {
      return "SELECT id FROM "
          + TABLE_NAME
          + " WHERE catalog_name = #{catalog} AND namespace = #{namespace}"
          + " AND table_name = #{table} AND state IN ('PENDING', 'RUNNING') LIMIT 1";
    }

    String pruneFinishedBefore(@Param("updatedBefore") long updatedBefore) {
      return "DELETE FROM "
          + TABLE_NAME
          + " WHERE state IN ('SUCCEEDED', 'FAILED') AND updated_at < #{updatedBefore}";
    }

    String selectState(@Param("id") long id) {
      return "SELECT state FROM " + TABLE_NAME + " WHERE id = #{id}";
    }
  }
}
